ALTER TABLE "Questionnaire" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "Questionnaire" ADD COLUMN IF NOT EXISTS "adminAccessMode" TEXT NOT NULL DEFAULT 'OWNER_AND_GROUP';
ALTER TABLE "Questionnaire" ADD COLUMN IF NOT EXISTS "adminGroupIds" JSONB NOT NULL DEFAULT '[]'::jsonb;
