ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "importedByUserId" TEXT;

ALTER TABLE "Group" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "Group" ADD COLUMN IF NOT EXISTS "importedByUserId" TEXT;

ALTER TABLE "ObjectEntity" ADD COLUMN IF NOT EXISTS "importedByUserId" TEXT;

ALTER TABLE "RoleDefinition" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "RoleDefinition" ADD COLUMN IF NOT EXISTS "importedByUserId" TEXT;
ALTER TABLE "RoleDefinition" ADD COLUMN IF NOT EXISTS "adminGroupIds" JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE "ObjectGroup" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "ObjectGroup" ADD COLUMN IF NOT EXISTS "importedByUserId" TEXT;
ALTER TABLE "ObjectGroup" ADD COLUMN IF NOT EXISTS "adminGroupIds" JSONB NOT NULL DEFAULT '[]'::jsonb;
